config/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('shortener.urls')),
]

admin.site.site_title = 'TURSH'
admin.site.site_header = 'TURSH Administration'
admin.site.index_title = 'TURSH Admin'

shortener/urls.py
from django.conf.urls import url
from . import views


app_name = 'shortener'


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^shorten_url/$', views.shorten_url, name='shorten_url'),
    url(r'^process_widget/$', views.process_widget, name='process_widget'),
    url(r'^widget/$', views.widget, name="widget"),
    url(r'^(?P<short_url>[0-9A-Za-z]{6})/$', views.redirect_original, name='redirect_original'),
]

assets/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Tursh{% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
    </head>
    <body>
        <div class="container-fluid">
            <br /><br />
            <div class="row">
                <div class="col-xs-offset-3 col-xs-6">
                    <div class="row">
                        <h1 class="text-center">{% block header %}<a href="{% url 'shortener:index' %}">Tiny Url Shortener</a>{% endblock %}</h1>
                        <p class="text-center">Ad-free url shortener</p>
                        <hr />
                    </div>

                    {% block content %}
                    <p>No Content</p>
                    {% endblock %}
                </div>
            </div>
        </div>
        
        <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/knockout.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/cookiejs.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/clipboard.min.js' %}"></script>
    </body>
</html>

assets/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        {% csrf_token %}
        <p style="color: red; font-weight: bold; visibility: hidden" id="pFullUrlError">full url error</p>
        <div class="row" style="margin-bottom: 10px">
            <div class="col-xs-9">
                <input class="form-control input-md" type="text" name="full_url" id="shortenedUrl" placeholder="Enter Full URL" maxlength="2000"/>
            </div>
            <div class="col-xs-3" id="btnDiv">
                <button class="form-control btn-primary" type="button" id="submitForm">Shrink</button>
            </div>
        </div>
        <p style="color: red; font-weight: bold; visibility: hidden" id="pShortUrlError">short url error</p>
        <div class="row">
            <div class="col-xs-9">
                <input type="text" class="form-control input-md" name="short_url" placeholder="Enter short URL" data-bind="visible: customShortUrl" maxlength="6"/>
            </div>
        </div>
        <div class="row">
            <input id="chkShortUrl" type="checkbox" style="margin-left: 15px; margin-top: 10px" data-bind="checked: customShortUrl"/>Custom short url
        </div>
    </div>
    <hr />
    <div class="row">
        <h3 class="text-center">How to embed widget on your website</h3>
        <p class="text-left">1. Add &lt;script type="text/javascript" src="http://www.tursh.net/widget/"&gt;&lt;/script&gt; to the head or below the body of your website.</p>
        <p class="text-left">2. Add &lt;div id="tursh_widget" widgetType="short" customStyle="false"&gt;&lt;/div&gt;</p>
        <p class="text-left">* id="tursh_widget" is compulsory. The div with that id will contain the widget's html. You have to make sure you don't have more than 1 element with that id.</p>
        <p class="text-left">* widgetType="short" or widgetType="long". Default is short. If no widgetType is specified or an invalid value was specified, the default value is used.</p>
<p class="text-left">* customStyle="false" or customStyle="true". Default is false. It is used to specify whether you want to apply a customStyle or not. If no value is specified or an invalid value is specified, the default value is used.</p>
    </div>
{% endblock %}